title: "UCSB CS8"
course: "CS8"
github_url: https://github.com/ucsb-cs8/ucsb-cs8.github.io

legacy_wiki_name: 8wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/8wiki" 

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/

instructor: https://ucsb-cs8.github.io/instructor

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:

  tutorials:
    output: true
    permalink: /tutorials/:path/

  topics:
    output: true
    permalink: /topics/:path/

  ptopics:
    output: true
    permalink: /ptopics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/
    
  instructors:
    output: true
    permalink: /instructors/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
  - scope:
      path: ""
      type: ptopics
    values:
      layout: topic
  - scope:
      path: ""
      type: resources
    values:
      layout: topic
  - scope:
      path: ""
      type: instructor
    values:
      layout: topic
